# Generated by Django 4.0.5 on 2022-06-14 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('toy_category', models.CharField(default='', max_length=200)),
                ('release_date', models.DateTimeField(default=datetime.datetime(2022, 6, 14, 18, 50, 30, 764914, tzinfo=utc))),
                ('was_home', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
